version: '3.8'

services:
  frontend:
    volumes:
      - ./frontend/nginx.local.conf:/etc/nginx/conf.d/default.conf
    # We only need port 80 for local dev
    ports:
      - "80:80"

  # Disable certbot for local development
  certbot:
    entrypoint: ["echo", "Certbot disabled locally"]
    restart: "no"
